# Generated by Django 5.0.2 on 2024-02-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0002_rename_name_image_rename_image_image_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
