# Generated by Django 5.0.2 on 2024-02-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0003_user_delete_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Id',
        ),
    ]
