# Generated by Django 5.0.2 on 2024-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0003_alter_id_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Id',
        ),
    ]
