# Generated by Django 5.0.2 on 2024-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0004_img_delete_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('doc', 'Word Document')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
