# Generated by Django 5.0.2 on 2024-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0005_exportedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportedfile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='exportedfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='exportedfile',
            name='file',
            field=models.FileField(null=True, upload_to='exported_files'),
        ),
        migrations.AlterField(
            model_name='exportedfile',
            name='format',
            field=models.CharField(max_length=10),
        ),
    ]
