# Generated by Django 5.0.2 on 2024-05-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0006_rename_created_at_exportedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportedfile',
            old_name='uploaded_at',
            new_name='exported_at',
        ),
    ]
