# Generated by Django 5.0.2 on 2024-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0007_rename_uploaded_at_exportedfile_exported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='img',
            name='preprocessed_ref',
            field=models.ImageField(null=True, upload_to='preprocessed_images'),
        ),
    ]
