# Generated by Django 5.0.2 on 2024-05-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0008_img_extracted_text_img_preprocessed_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedfile',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_files', to='invoiceScanApp.img'),
        ),
    ]
