# Generated by Django 5.0.2 on 2024-05-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceScanApp', '0010_rename_img_exportedfile_img_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportedfile',
            old_name='img_ref',
            new_name='img_id',
        ),
    ]
